import Head from 'next/head'
import type { NextPage } from 'next'
import { useState } from 'react'

const Home: NextPage = () => {
  const [userName, setUserName] = useState("");
  const [password, setPassword] = useState("");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>ts-nextjs-express starter</h1>
    </div>
  )
}

export default Home
